# -*- coding: utf-8 -*-
"""tutorial3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sejxLq4oV5UCqa583NsBDgGijDcm-sQY
"""

import numpy as np

# task 1
array = np.array([[0, 3], [2, 5]])
print(array.shape)

# task 2
np.random.seed(0)
x = np.random.randint(8, size=(3, 4))
print(x)

# task 3
x = np.ones((3, 3))
y = np.zeros((3, 3))
print(x, y)

# task 4
np.random.seed(0)
x = np.random.randint(10, size=(6, 3))
print(x.T)

# task 5
np.random.seed(0)
n = np.random.randint(1, 10)
p = np.random.randint(1, 10)
m = np.random.randint(1, 10)
x = np.random.randint(10, size=(n, p))
y = np.random.randint(10, size=(p, m))
print(x.dot(y))

# i have finished this task